### ISSUE TITLE
Do you have an example of a font that can be successfully converted?

### ISSUE THREAD

**Issue by indianakernick** [koron/bdf2ttf#6]
At first, I tried converting a minimal handwritten file. `bdf2tff` didn't emit any error messages but produced an invalid font. I tried converting [this font](https://github.com/Tecate/bitmap-fonts/blob/master/bitmap/cherry/cherry-10-r.bdf) and still got no error messages but an invalid ttf file. This is the debug output.

```
Input files:
  cherry.bdf
bdf2_load: size=10
bdf2_load: create a font size 10
bdf_load: encoding is 8859-1
bdf2_load: numGlyph=191
bdf2_get_count()=1
n_coresize=10
  emX=1024
  emY=1024
  emAscent=1024
  emDescent=0
bdf2_t.sizelist:
  10: w=6 h=10 ascent=8 descent=2
```

The `name` and `sbit` tables of the resulting ttf files are invalid somehow. That's all I know. Maybe the bdf file is invalid? Could you provide me with a minimal bdf file with just one glyph that produces a valid ttf file?

**Comment by koron** [comment]
I don't have any examples anymore, because this is very old project to me.

But you can find some examples in Japanese by others on Google.
http://hp.vector.co.jp/authors/VA023367/twitter_disp/elisa-font/create_font.html
